Implemented swipe transitions on connecting ledger
Moonlet/wallet-app pull request #1051
Opened 2020-10-06 23:46 UTC by standreinmcp

2020-10-06 23:48 UTC, krisboit approved these changes

2020-10-06 23:48 UTC, krisboit commented on src/screens/ledger/ledger-connect-component.tsx
> +                duration: FADE_ANIMATION_TIME,
since this is not a fade animation anymore, it's confusing to have this name. Change it to a more generic name `ANIMATION_TIME` for example.

2020-10-07 19:33 UTC, georgeburduhos approved these changes

2020-10-07 20:50 UTC, NovacAndrei requested changes

2020-10-07 20:50 UTC, NovacAndrei commented on src/screens/ledger/ledger-connect-component.tsx
> +    private async stepContainerFadeOut(step: ScreenStep) {
`step` it's not used in the function

2020-10-07 20:50 UTC, NovacAndrei commented on src/screens/ledger/ledger-connect-component.tsx
> +                // easing: Easing.out(Easing.exp)
delete if not needed

2020-10-08 13:07 UTC, NovacAndrei approved these changes

2020-10-08 13:07 UTC, merged