Claim all
Moonlet/wallet-app pull request #1311
Opened 2020-11-13 14:56 UTC by NovacAndrei

2020-11-13 21:44 UTC, krisboit requested changes

2020-11-13 21:44 UTC, krisboit commented on src/redux/ui/screens/data/actions.ts
> +            appVersion: __DEV__ ? '1.4.18' : DeviceInfo.getVersion(),
there is no need for this, we can just change the version in package json as we need

2020-11-16 09:55 UTC, krisboit approved these changes

2020-11-16 10:41 UTC, georgeburduhos approved these changes

2020-11-16 10:47 UTC, merged