update erc 20
Moonlet/wallet-app pull request #1433
Opened 2021-04-26 14:04 UTC by georgeburduhos

2021-04-26 14:15 UTC, NovacAndrei approved these changes

2021-04-27 10:01 UTC, krisboit requested changes

2021-04-27 10:01 UTC, krisboit commented on src/core/wallet/hw-wallet/ledger/apps/eth.ts
> +            if (tokenInfo) await this.app.provideERC20TokenInformation(tokenInfo);
this should be done only if tx is a ERC20 tx, for normal smart contracts not.

2021-04-27 15:30 UTC, georgeburduhos commented on src/core/blockchain/ethereum/client-utils.ts
> +                status = tx.status;
It's used above in case we have the status code. If we have address only we use getTransaction

2021-04-28 07:36 UTC, NovacAndrei approved these changes

2021-04-28 12:02 UTC, krisboit approved these changes

2021-04-28 12:10 UTC, merged