Implemented Ethereum name service
Moonlet/wallet-app pull request #926
Opened 2020-09-16 10:45 UTC by standreinmcp

2020-09-16 10:50 UTC, georgeburduhos commented on src/core/blockchain/types/name-service.ts
> +    resolveName(text: string): Promise<string | IResolveNameResponse>;
Always respond with IResolveNameResponse and add address inside the object

2020-09-16 19:14 UTC, krisboit requested changes

2020-09-17 05:46 UTC, standreinmcp commented on src/screens/send/send.tsx
> +                        nameService
I passed as nameService as an optional prop and then if it exists, immediately return it

2020-09-17 09:56 UTC, krisboit requested changes

2020-09-17 09:56 UTC, krisboit commented on src/core/utils/format-address.ts
> +    if (nameService !== '') {
we can be smarter :) 
```ts
if (text.match(/.+\.[a-zA-Z]{2,}$/gi)) return text;
```
so you don't really need an extra parameter

2020-09-21 22:23 UTC, krisboit approved these changes

2020-09-22 05:00 UTC, georgeburduhos approved these changes

2020-09-22 05:08 UTC, merged